### PR TITLE
Add Basic Tests

### PR DESCRIPTION
**Pull request by lukeed**
So far, just validating the happy path. Would like to test error outputs, but a lot of that relies on better `gittar` errors: https://github.com/lukeed/gittar/issues/1

### CODE REVIEW

**Comment by lukeed** [comment]
Modified Travis so that it only builds the `master` branch & any PRs. Also turned `coveralls` back on, oops.

**Comment by lukeed** [comment]
Guess I didn't turn Coveralls back on after all 😒 lol

**Comment by lukeed** [comment]
Even though this migration is still very much WIP, do you want to cut a `0.2.0` after this? Can start using it locally.

**Review by vutran — APPROVED** [review]
Looks great! (Apologies, still recovering from outsidelands)

**Comment by lukeed** [comment]
No prob, that was me a few years ago. ☠️

**Comment by vutran** [comment]
Let's cut the `0.2.0` today. I'm going to seek to open a schedule this week for some OSS to do some research for reimplementing the dotfile.

**Pull request merged**
