### PR TITLE
check in flow-typed definitions

### PR DESCRIPTION
**Pull request by vutran**
I'm open for discussions on this but I feel like `flow-typed` definitions should be checked in instead of being gitignored and hooked into the `postinstall` script. This allows users to consume the tool without having to go through `postinstall`. At the moment, the tool currently breaks upon installation as it's calling `flow-typed install` which only exists as a `devDependency`.

Another alternative is to run `flow-typed install` on a DEV-only environment.

### CODE REVIEW

**Comment by lukeed** [comment]
Yeah, I really don't think these should be checked in to the repo. However, I forgot that `postinstall` runs on a "production" install too. 

So I think the script should be renamed as is, and is to be run in a dev env. 🤔

**Comment by lukeed** [comment]
That said, this is just my gut feeling as I don't use any part of the ecosystem. Do what you see is best!

**Comment by vutran** [comment]
I'll leave this open for now until I can find another solution cause I feel the same since it's 3rd-party definitions.

**Comment by vutran** [comment]
Closing this in favor of #48

**Pull request closed without merging**
